baseURL ="https://sklavenitis-pl.onrender.com"
languageCode = "el"
title = "Τα Προϊόντα Ιδιωτικής Ετικέτας"
paginate = "12"
paginatePath = ""
removePathAccents = false
assetDir = "static"

[taxonomies]
  tag = "tags"
  category = "categories"
  
  gencat= "gencat"
  publication_type = "publication_types"
  author = "authors"
  layout = ""

[outputs]
  home = ["HTML", "json"]

[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 75
  resampleFilter = 'Box'


