baseURL ="https://sklavenitis-pl.onrender.com"
languageCode = "el"
title = "Τα Προϊόντα Ιδιωτικής Ετικέτας"
paginate = "8"
paginatePath = ""
removePathAccents = false

[taxonomies]
  tag = "tags"
  category = "categories"
  
  gencat= "gencat"
  publication_type = "publication_types"
  author = "authors"
  layout = ""

[outputs]
  home = ["HTML"]


