baseURL ="https://sklavenitis-pl.onrender.com"
languageCode = "el"
title = "Τα Προϊόντα Ιδιωτικής Ετικέτας"
paginate = "12"
paginatePath = ""
removePathAccents = false

[taxonomies]
  tag = "tags"
  category = "categories"
  smeta= "smeta"
  publication_type = "publication_types"
  author = "authors"
  layout = ""

[outputs]
  home = ["HTML"]


